### ISSUE TITLE
external submodule not available

### ISSUE THREAD

**Issue by mars3142** [Squalr/cocos2d-x#5]
It's not possible to checkout the complete source code, because the external submodule isn't available (not public).

**Comment by mattbucci** [comment]
@mars3142 thanks for pointing this out, it looks like the repo is still pointing to the old repo, the new submodule is available here: https://github.com/Squalr/cocos-external/tree/56fece7771d9d3a1e9492414af6dc18acbe6a323

**Comment by zcanann** [comment]
Repo updated to point to the correct submodule
